### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/tabulizer#148]
Or new maintainer team. :smile_cat: 

In particular it'd be urgent to fix #140 for which there is a PR #146 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

@tpaskhalis your contributions are still most welcome, but hopefully someone can help get tabulizer in shape again.

**Comment by maelle** [comment]
@ropensci/admin

**Comment by pachadotdev** [comment]
hi!
happy to collaborate, because I'll be using this package intensively

**Comment by maelle** [comment]
@pachadotdev thank you! If no one else volunteers, would you be ok being the sole maintainer of tabulizer?

**Comment by pachadotdev** [comment]
> @pachadotdev thank you! If no one else volunteers, would you be ok being the sole maintainer of tabulizer?

yes

**Comment by maelle** [comment]
Thank you, I've now given you admin access to this repository (and to tabulizerjars)!

**Comment by pachadotdev** [comment]
> 

merci, @maelle
Je ferai de mon mieux pour apporter une bonne contribution.
