### ISSUE TITLE
Is the package abandoned?

### ISSUE THREAD

**Issue by b-rodrigues** [ropensci/tabulizer#160]
Trying to install this package results in following error message:

```
package 'tabulizer' is not available for this version of R
```
 
Visiting https://cran.r-project.org/web/packages/tabulizer/index.html shows that the package was removed from CRAN.

The package is available on r-universe and successfully installs from there: https://ropensci.r-universe.dev/tabulizer  

Will the package only going to be available through r-universe going forward? If yes, this should be mentioned in the readme.

**Comment by pachadotdev** [comment]
Hi

In the short term, yes. Just r universe for now

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Bruno Rodrigues ***@***.***>
Sent: Wednesday, September 27, 2023 11:04:18 AM
To: ropensci/tabulizer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ropensci/tabulizer] Is the package abandoned? (Issue #160)


Trying to install this package results in following error message:

package 'tabulizer' is not available for this version of R


Visiting https://cran.r-project.org/web/packages/tabulizer/index.html shows that the package was removed from CRAN.

The package is available on r-universe and successfully installs from there: https://ropensci.r-universe.dev/tabulizer

Will the package only going to be available through r-universe going forward? If yes, this should be mentioned in the readme.
