### ISSUE TITLE
Password Protection error for PDF's without PW protection

### ISSUE THREAD

**Issue by methodds** [ropensci/tabulizer#18]
Hi,

I'm having trouble  with some PDFs (which work with the tabula browser). When trying to load them with  `extract_areas`` the following error is raised:

```
f <- "path_to_pdf/0101.pdf"
out1 <- extract_areas(f, pages=c(1))

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.io.IOException
In addition: Warning messages:
1: In load_doc(file, password = password) :
  PDF appears to be password protected and no password was supplied.
2: In load_doc(file, password = password) :
  PDF appears to be password protected and no password was supplied.
```

An example PDF is available here:
http://www.insee.fr/fr/ppp/bases-de-donnees/donnees-detaillees/circo_leg/donnees/0101.pdf
It is not password protected.

**Comment by leeper** [comment]
Thanks. I'll investigate.

**Comment by leeper** [comment]
This PDF appears to no longer be available. Please let me know if you're still encountering this issue. If so, I will reopen.
