### ISSUE TITLE
is there a limit on the size of the extraction?

### ISSUE THREAD

**Issue by jli-vericred** [ropensci/tabulizer#19]
I tried to extract 816 pages using extract_tables from a PDF that has a size of 8.2MB. After 10 minutes of running, the following error message popped up:

`Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.OutOfMemoryError: Java heap space`

Would really appreciate your help!

Thank you!

**Comment by kevlu93** [comment]
Having the same issue, increased the memory available to 12 GB, now I get this error:

Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.apache.pdfbox.exceptions.WrappedIOException

**Comment by leeper** [comment]
The short term solution would be to use the `pages` argument and break this out into a few separate steps.

I'll look into a more robust solution.

**Comment by kevlu93** [comment]
So it looks like once I increase the heap size it'll always throw the ioexception no matter how many pages i set. Once I restart I can then extract a certain number of pages. (I'm currently testing what the upper bound is for my case)

**Comment by jli-vericred** [comment]
I increased the memory available to 16GB and it worked for me. Not sure the bound though.

**Comment by leeper** [comment]
@jli-vericred Can you confirm exactly what you did to solve this? I'd like to add something to the README about it given multiple users have encountered the issue.

**Comment by jli-vericred** [comment]
It's been a while, but I think, if I remember correctly, I used the following:

`options(java.parameters = "-Xmx16000m")`

**Comment by leeper** [comment]
Thanks!

**Comment by robsalasco** [comment]
Thank you!
