### ISSUE TITLE
Specifying area and using nospreadsheet=True doesn't work 

### ISSUE THREAD

**Issue by Kanz95** [ropensci/tabulizer#33]
I have a pdf where guessing or autodetect tables isn't able to find the table and the table is a Stream table(columns separated by white spaces). I used tabula-py where the code goes like:

`df=tabula.read_pdf("sample.pdf",nospreadsheet=True,area=(321.3,49.459,836.719,567.109))
`
I get an empty dataframe after executing .But mentioning the same area and using it through tabula in windows produces me a output which is what i want.

is there any way?

**Comment by leeper** [comment]
What was the R code you used? The analogue should be:

```r
extract_tables("sample.pdf", spreadsheet = FALSE, area = list(c(321.3,49.459,836.719,567.109)))
```

You  may want to try with `guess = FALSE`, as well:

```R
extract_tables("sample.pdf", spreadsheet = FALSE, guess = FALSE, area = list(c(321.3,49.459,836.719,567.109)))
```

**Comment by Kanz95** [comment]
@leeper  Worked! Thanks
