### ISSUE TITLE
annoying warning

### ISSUE THREAD

**Issue by kforner** [ropensci/tabulizer#36]
Hello,
I get plenty of messages:

> There is already a file with this name in the temporary directory. It will be overwritten.

I saw that they come from localize_file(). It seems that the temp path (which is probably not needed for non-URL loaded files) is built using tempdir(), which explains the above message.
Why not using tempfile() to build a proper temporary path ? Or do not copy the file if it is not needed ?

P.S
tabulizer works great !

**Comment by leeper** [comment]
Yea, I have no idea why I did it that way. I'll put this on the todo list.
