### ISSUE TITLE
blank images in locate_areas and make_thumbnails

### ISSUE THREAD

**Issue by pboesu** [ropensci/tabulizer#37]
Hi, 

I'm having some issues with PDF files that I created from scans (TIFF -> adobe acrobat OCR -> PDF). `extract_tables` works fine on most of them, but occasionally misses the last row of a table. I therefore tried to get better results with `locate_areas`. However, the shiny app simply shows an empty image. The same happens when I use `make_thumbnails` on these files; a blank PNG is created.

Both functions work fine with the demo file that ships with the package, so I suspect that it has something to do with the PDF I created. Do I need to enable particular PDF features when I collate the scanned TIFs?

For completeness sake, below is my sessionInfo. I also tried to attach a sample PDF, but that currently fails (I suspect because of the ongoing S3 issues). I'll try again later.
```
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.0.0      tabulizer_0.1.23

loaded via a namespace (and not attached):
 [1] tabulizerjars_0.1.2 R6_2.2.0            htmltools_0.3.5     tools_3.3.2         Rcpp_0.12.9         jsonlite_1.2        digest_0.6.12      
 [8] xtable_1.8-2        httpuv_1.3.3        miniUI_0.1.1        mime_0.5            rJava_0.9-8         png_0.1-7 
```

**Comment by leeper** [comment]
Does that occur with all image formats (not just png)?

**Comment by pboesu** [comment]
Yes. Empty images for all formats.

I've provided a self contained example here: https://github.com/pboesu/tabulizer_example

**Comment by leeper** [comment]
After having looked over this, I suspect tabulizer is not the right tool here. Because these are scans, the information is actually stored as images. Perhaps something like `plot(magick::image_read(pdftools::pdf_render_page(f)))` will get you closer to what you need. I don't think PDFBox is designed to handle images in PDFs very well.
