### ISSUE TITLE
extract_tables() doesn't work with the new update

### ISSUE THREAD

**Issue by maskegger** [ropensci/tabulizer#38]
Hi,

All my packages were deleted due to some stupid mistake. Upon reinstalling (in windows), extract_tables() doesn't work anymore and gives me this error. 
```
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  java.lang.IllegalArgumentException: Comparison method violates its general contract!
```
I reinstalled java and but it gives me the same error. I tried repeating the process on my mac as well and it shows the same error. Is there something I'm doing wrong?

**Comment by leeper** [comment]
Can you make a fully reproducible example?
