### ISSUE TITLE
Error using get_n_pages()

### ISSUE THREAD

**Issue by snoopyhaimaxuan** [ropensci/tabulizer#40]
Hi, an error as follows occurred when I tried to get the number of pages of a PDF file. I am not sure if it's because of the size of the file, but increasing the JAVA memory didn't help. 

`Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  org.apache.pdfbox.exceptions.WrappedIOException`

Thank you!

**Comment by leeper** [comment]
Is this on all PDFs or one specific file? If the former, can you make a reproducible example? If the latter, can you share the PDF?

**Comment by snoopyhaimaxuan** [comment]
Hi, Thank you for the reply!
It only happened to a specific PDF (I used the try-error function to avoid temporarily, so I don't know if this is the only one). Oops the file is too large, so I pasted the address to it. 
http://static.globalreporting.org/report-pdfs/2011/4038e784aca44d8098c6b7726cc85095.pdf

**Comment by leeper** [comment]
Thanks. I'll investigate.
