### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by eaglechan123** [ropensci/tabulizer#41]
I have tried to install in RStudio both

> ghit::install_github(c("ropenscilabs/tabulizerjars", "ropenscilabs/tabulizer"), INSTALL_opts = "--no-multiarch")

and

> ghit::install_github(c("leeper/tabulizerjars", "leeper/tabulizer"), INSTALL_opts = "--no-multiarch", dependencies = c("Depends", "Imports"))

according to http://stackoverflow.com/questions/39132202/trouble-installing-tabulizer-package-for-r

but the result shows 

> 'leeper/tabulizerjars     leeper/tabulizer 
>              "0.1.2"                                        NA 
> There were 20 warnings (use warnings() to see them)'

There is tabulizerjars in the library but not tabulizer.

when i typed

>  'install_github("ropensci/tabulizer")'

 it shows

> Error in read.dcf(file = tmpf) : cannot open the connection
> In addition: Warning message:
> In read.dcf(file = tmpf) :
>   cannot open compressed file 'c:\temp\RtmpWQoyv5/ghitdrat/src/contrib/PACKAGES', probable 

> reason 'No such file or directory'

When I typed 

> ghit::install_github("leeper/tabulizer", INSTALL_opts = "--no-multiarch")
it shows 

> leeper/tabulizer 
              NA 

Anyone know how to solve this please? There is no tabulizer in the library at the moment.

Thank You.

**Comment by leeper** [comment]
Can you run this with the argument `verbose = TRUE`? It will better show where the error is occurring.

**Comment by eaglechan123** [comment]
When I typed

> ghit::install_github("leeper/tabulizer", INSTALL_opts = "--no-multiarch",verbose = TRUE)

it shows

> Parsing reponame for 'leeper/tabulizer'...
Creating local git repository for tabulizer in c:\temp\RtmpOeaCdv\tabulizer2e1019602f0f...
Checking out package tabulizer to local git repository...
[new]     378614083d16b033f0f7 refs/remotes/github/master
Adding metadata to DESCRIPTION for package tabulizer...
Reading package metadata for 'leeper/tabulizer'...
Installing 'Suggests' packages for 'tabulizer': graphics, grDevices, shiny, miniUI, testthat, knitr
Installing packages into 慐:/document/R/win-library/3.3?(as 憀ib?is unspecified)
system (cmd0): C:/PROGRA~1/R/R-33~1.3/bin/x64/R CMD INSTALL --no-multiarch
Error in read.dcf(file = tmpf) : cannot open the connection
In addition: Warning message:
In read.dcf(file = tmpf) :
  cannot open compressed file 'c:\temp\RtmpOeaCdv/ghitdrat/src/contrib/PACKAGES', probable reason 'No such file or directory'

**Comment by leeper** [comment]
Can you try installing with `devtools::install_github("leeper/tabulizer")`?

**Comment by eaglechan123** [comment]
It worked. Thank you.

I am new to R and trying your example. For your first example, after i typed the following, it shows list of 3 instead of list of 4

> str(out1)
List of 3
 $ : chr [1:32, 1:10] "mpg" "21.0" "21.0" "22.8" ...
 $ : chr [1:7, 1:3] "Sepal.Width" "3.5" "3.0" "3.2" ...
 $ : chr [1:15, 1] "supp" "VC" "VC" "VC" ...

Also, when I try to export it to excel using

>  write.xlsx(out1,file='aba.xlsx')
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  arguments imply differing number of rows: 32, 7, 15
Do you have any idea what is wrong with it?

Thank You.

**Comment by leeper** [comment]
Glad you got it to work. I'm not sure what the problem is with the `write.xlsx()` code.
