### ISSUE TITLE
How to install from local directory?

### ISSUE THREAD

**Issue by lmmonline** [ropensci/tabulizer#51]
Hi I have downloaded the zip file to C:/Users/Public. 
My operating system is windows7 64 bit.  My version of R is 3.3.2
 I have tried ...
```
> install.packages('C:/Users/Public/tabulizer-master.zip', repos = NULL, type="binary", INSTALL_opts = "--no-multiarch")
> library(`tabulizer-master`)
Error in library(`tabulizer-master`) : 
  there is no package called ‘tabulizer-master’
> library(`tabulizer`)
Error in library(tabulizer) : there is no package called ‘tabulizer’
```

I have also tried

```
 ghit::install_github(c("leeper/tabulizerjars", "leeper/tabulizer"), INSTALL_opts = "--no-multiarch", verbose = TRUE) 
Parsing reponame for 'leeper/tabulizerjars'...
Creating local git repository for tabulizerjars in C:\Users\MARSHL~1\AppData\Local\Temp\RtmpqkiGbZ\tabulizerjarsa0c2a8e4674...
Checking out package tabulizerjars to local git repository...
Error in git2r::fetch(gitrepo, name = "github", credentials = credentials) : 
  Error in 'git2r_remote_fetch': failed to send request: A connection with the server could not be established

> devtools::install_github("leeper/tabulizer")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't connect to server
```
Can you please give some instructions for installing tabulizer from a local zip files? Thank you.

**Comment by leeper** [comment]
You cannot install from the zip file downloaded from GitHub. You have to unzip it, then run `R CMD build tabulizer` in command prompt. If you're not experienced doing that, I wouldn't try. Instead, I would try to resolve the internet connection issue that is clearly preventing you from installing directly from GitHub. Are you behind a strict firewall or using a proxy server to connect to the internet?

**Comment by lmmonline** [comment]
Thanks for you answer leeper, I have been installing from CRAN with no problem, and as  this is not the computer I usually use with github this makes me think the credentials required are for github and this is what I need to sort out to fix the connection issue. I just thought it may be faster to install from local but from what you are saying probably not. That's OK there are guides for github which I can follow.
