### ISSUE TITLE
locate_areas() widget issue

### ISSUE THREAD

**Issue by moman822** [ropensci/tabulizer#52]
I am getting the following error when using `locate_areas()` with the native or reduced widgets;

```
Graphics device does not support event handling...
Entering reduced functionality mode.
Click upper-left and then lower-right corners of area.
Error in try_area_reduced(file = file, dims = dims, area = area, warn = warn) : 
  Graphics device does not support rasterImage() plotting
```

When searching this error, I was led to [this](https://github.com/ropensci/tabulizer/blob/master/R/try_area_methods.R) file: `try_area_methods.R`

Looking on line 74 there is this condition that shows the final line of my error: 
```
if (grDevices::dev.capabilities()[["rasterImage"]] != "no") {
        stop("Graphics device does not support rasterImage() plotting")
    }
```
There is also this similar condition on line 103 (note the `!=` vs `==` while producing the same error):
```
if (grDevices::dev.capabilities()[["rasterImage"]] == "no") {
        stop("Graphics device does not support rasterImage() plotting")
    }
```

Having checked my `grDevices::dev.capabilities()`, rasterImage is enabled and so I would think this error would not apply to me. Is the condition from line 74 flipped and causing this error?

I attempted to clone the repo and make the change myself but couldn't figure out how to install locally, so I am pointing it out here.

**Comment by leeper** [comment]
I've just patched this. Can you try reinstalling and see if it's working for you?

**Comment by moman822** [comment]
It is! Thank you, and great package.
