### ISSUE TITLE
Use extract_areas() within Shiny app

### ISSUE THREAD

**Issue by moman822** [ropensci/tabulizer#53]
I am receiving the following error when attempting to use `extract_areas()` within a Shiny app:

`Warning: Error in shiny::runApp: Can't call `runApp()` from within `runApp()`. If your ,application code contains `runApp()`, please remove it.`

I gather that this is because `extract_areas()` calls/creates its own Shiny app and that is not allowed within an already existing Shiny environment. I am wondering if there is a solution or workaround to this, or if it has been addressed before. Thanks!

PS. I have attempted to use `locate_areas(..., widget='native') and this does start to work and allows me to click the areas in the RStudio viewer pane, but freezes (and requires force quit on RStudio) once all pages have been "located" on. I have not attempted to upload this solution to a server.

**Comment by leeper** [comment]
I guess I wouldn't try to do this. It's a complete app, not a widget, so I don't know how you could incorporate it into another app.
