### ISSUE TITLE
Error installing unable to init repository

### ISSUE THREAD

**Issue by ogorodriguez** [ropensci/tabulizer#54]
When I try to install tabulizer after activating png and rJave this is the error I receive:

```R
> ghit::install_github(c("leeper/tabulizerjars", "leeper/tabulizer"), INSTALL_opts = "--no-multiarch", dependencies = c("Depends", "Imports"))
Error in git2r::init(d) : 
  Error in 'git2r_repository_init': Unable to init repository
```

I have searched online for such type of error and haven't found anything related.  Any help on this issue will be highly appreciated.

**Comment by ogorodriguez** [comment]
On the other hand when I try with devtools...  I get the error command  failed (1)  What could be the issue?  Willing to provide more info regarding my system if indicated.  New to R.  Thanks in advance.

devtools::install_github(c("leeper/tabulizerjars", "leeper/tabulizer"), args = "--no-multiarch", dependencies = c("Depends", "Imports"))
Downloading GitHub repo leeper/tabulizerjars@master
from URL https://api.github.com/repos/leeper/tabulizerjars/zipball/master
Installing tabulizerjars
"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL "C:/Users/Luis  \
  Jerez  \
  Rincón/AppData/Local/Temp/Rtmpye4gRU/devtools4fb04bc31ff2/ropensci-tabulizerjars-c6cc40e"  \
  --library="C:/Users/Luis Jerez  \
  Rincón/Documents/R/win-library/3.3" --install-tests  \
  --no-multiarch 

* installing *source* package 'tabulizerjars' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Luis Jerez Rincsn/Documents/R/win-library/3.3/tabulizerjars/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  cannot open the connection
ERROR: installing package DESCRIPTION failed for package 'tabulizerjars'
* removing 'C:/Users/Luis Jerez Rincón/Documents/R/win-library/3.3/tabulizerjars'
Error: Command failed (1)

**Comment by leeper** [comment]
I think you lack write permission for your own R library directory. Try running R as an administrator or change the permissions for your directories.

**Comment by ogorodriguez** [comment]
Thanks for the prompt reply.  I have tried running as admin (rstudio as an admin) and I still get the same error.  How can I change the permissions for my directories?

**Comment by leeper** [comment]
Looking again I think it may be because the path to your temporary directory is not an ASCII string (due to your account's user name). You might try changing the temporary directory using environment variables, perhaps:

```R
Set.envvar(TMPDIR = "C:/somewhere")
```

And then try the installation again. If you use ghit, set `verbose = TRUE` to get more information about where exactly this failed.

**Comment by DanStrobridge** [comment]
I'm also having an installation problem despite running Rstudio as an administrator and setting an environmental variable TMPDIR to C:\Windows\TEMP.  The information returned with verbose=TRUE is below:

``ghit::install_github(c("ropensci/tabulizerjars", "ropensci/tabulizer"), INSTALL_opts = "--no-multiarch", verbose = TRUE)
Parsing reponame for 'ropensci/tabulizerjars'...
Creating local git repository for tabulizerjars in C:/Users/strobrid/AppData/Local/Temp\RtmpILFPlb\tabulizerjarsbeb5c3c8f7d5a...
Checking out package tabulizerjars to local git repository...
[new]     c6cc40e055d3f92c4e96 refs/remotes/github/master
[new]     8e97b66b202b72e2d3b8 refs/remotes/github/tabula1.0.0
[new]     49e8e460fd627b6b05db refs/tags/v0.8.0
[new]     9d4ad56ff7efa2f15560 refs/tags/v0.9.0
[new]     063903e22684b86ad1e5 refs/tags/v0.9.1
[new]     e472789f3d7f3e3e7a6b refs/tags/v0.9.2
[new]     8cd728692a47868b4fff refs/tags/v1.0.1
Adding metadata to DESCRIPTION for package tabulizerjars...
Reading package metadata for 'ropensci/tabulizerjars'...
Building package tabulizerjars (0.9.2)...
Using internal package repository in C:/Users/strobrid/AppData/Local/Temp\RtmpILFPlb/ghitdrat/src...
Writing PACKAGES file for internal repository...
tar (child): Cannot connect to C: resolve failed
gzip: [standard input]: not in compressed format
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
reading DESCRIPTION for package ‘tabulizer’ failed with message:
  cannot open the connection
tar (child): Cannot connect to C: resolve failed
gzip: [standard input]: not in compressed format
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
reading DESCRIPTION for package ‘tabulizerjars’ failed with message:
  cannot open the connection
Writing PACKAGES file for Windows binaries in internal repository...
Writing package tabulizerjars to internal repository...
tar (child): Cannot connect to C: resolve failed
gzip: [standard input]: not in compressed format
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
reading DESCRIPTION for package ‘tabulizer’ failed with message:
  cannot open the connection
tar (child): Cannot connect to C: resolve failed
gzip: [standard input]: not in compressed format
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
reading DESCRIPTION for package ‘tabulizerjars’ failed with message:
  cannot open the connection``

**Comment by leeper** [comment]
@DanStrobridge Can you try installing "tabulizerjars" first? Also, you can try devtools instead of ghit, but it looks like your computer lacks a program for working with tar files.

**Comment by DanStrobridge** [comment]
tabulizerjars was first in the vector of packages and it didn't work.  I agree that it seems the tar file is the issue.  I'm not sure why though since I'm running the MKS Toolkit unix emulator required by another software.  I'll find a tool explicitly for tar files and add it directly onto my path variable.
