### ISSUE TITLE
Options for Lattice / Stream Mode ?

### ISSUE THREAD

**Issue by psychemedia** [ropensci/tabulizer#65]
The [`tabulapdf/tabula-java`](https://github.com/tabulapdf/tabula-java) packages and API seems to have moved on compared to `ropensci/tabulizer`, for example in terms of the `lattice` and `stream` options.

Is support for these planned?

I think these options make it easier to extract multiple tables from a single page, eg as queried in https://github.com/ropensci/tabulizer/issues/22 ?

**Comment by leeper** [comment]
`lattice` is the new name for `spreadsheet`. `stream` is not supported in tabulizer (yet).

**Comment by tpaskhalis** [comment]
The `stream` option in Tabula is essentially equivalent to `spreadsheet = FALSE` in tabulizer. While `lattice` would be `spreadsheet = TRUE`. I restructured the code to be consistent with Tabula nomenclature. It's available on the development branch: [tabulizer/pdfbox2.0](https://github.com/tpaskhalis/tabulizer/tree/pdfbox2.0), which works together with the development branch of [tabulizerjars/tabula1.0.0](https://github.com/ropensci/tabulizerjars/tree/tabula1.0.0). So, something like that would work:
```
tab <- extract_tables(f, method = "stream")
```
The only key difference is that the default option `decide` as in the current version of Tabula applies to each page individually. Which, as you suggested, makes it somewhat easier to extract multiple inconsistent tables from one page.

**Comment by leeper** [comment]
@maelle I apparently don't have the ability to add contributors to this repo. Can you add @tpaskhalis, giving him edit/push rights here and on [tabulizerjars](https://github.com/ropensci/tabulizerjars)?

**Comment by maelle** [comment]
Ok so I

* Created a team and invited @tpaskhalis to it. The team has write access to this repo.

* Made you an admin @leeper 

Should the team also get write access to tabulizerjars?

**Comment by maelle** [comment]
Oops I should have read better am gonna add the second repo for the team sorry

**Comment by tpaskhalis** [comment]
Many thanks, @maelle!

**Comment by maelle** [comment]
Thank *you*!

**Comment by tpaskhalis** [comment]
The options are now available on the `master` branch  (#83). Please, update and reinstall the package. Check `?extract_tables` for further details.
