### ISSUE TITLE
Can't install tabulizerjars - unknown timezone error

### ISSUE THREAD

**Issue by ajduncanson** [ropensci/tabulizer#73]
I think I've followed all the install instructions for MacOS, but all I get in response to this:

ghit::install_github(c("ropensci/tabulizerjars", "ropensci/tabulizer"))

Is this:

Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'default/Australia/Sydney'

Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'default/Australia/Sydney'

ropensci/tabulizerjars     ropensci/tabulizer 
                    NA                     NA 
Warning messages:
1: In utils::install.packages(to_install, type = type, repos = repos,  :
  installation of package ‘tabulizerjars’ had non-zero exit status
2: In utils::install.packages(to_install, type = type, repos = repos,  :
  installation of package ‘tabulizer’ had non-zero exit status

**Comment by leeper** [comment]
Can you try reinstalling with either (a) setting `verbose = TRUE` to see where this is failing, or (b) use `devtools::install_github()` instead of `ghit`?

**Comment by ajduncanson** [comment]
Still nothing:

> devtools::install_github("ropensci/tabulizer", args="--no-multiarch", verbose=TRUE)

Downloading GitHub repo ropensci/tabulizer@master
from URL https://api.github.com/repos/ropensci/tabulizer/zipball/master
Installing tabulizer
Downloading GitHub repo ropensci/tabulizerjars@master
from URL https://api.github.com/repos/ropensci/tabulizerjars/zipball/master
Installing tabulizerjars
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/dv/0lw00zg90570m6vn80gzxh200000gn/T/Rtmp00AWvG/devtools500a311bf317/ropensci-tabulizerjars-60b7cec'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘tabulizerjars’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'default/Australia/Sydney'
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘tabulizerjars’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/tabulizerjars’
Installation failed: Command failed (1)
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/dv/0lw00zg90570m6vn80gzxh200000gn/T/Rtmp00AWvG/devtools500a7887d7d/ropensci-tabulizer-3aad163'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests --no-multiarch 

ERROR: dependency ‘tabulizerjars’ is not available for package ‘tabulizer’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/tabulizer’
Installation failed: Command failed (1)

**Comment by ajduncanson** [comment]
Seems there's an OSX / r problem with timezones so I used Sys.setenv(TZ="Australia/Sydney") to get passed that.

And struck a new error which I'll post separately....!
