### ISSUE TITLE
 unknown certificate check failure

### ISSUE THREAD

**Issue by marek1914** [ropensci/tabulizer#77]
The system ( Cran 3.4.2 as well as 3.4.3 64bit WIN7) worked fine with tabulizer, untill now
I got following error " unknown certificate check failure"

> > ghit::install_github(c("ropensci/tabulizerjars", "ropensci/tabulizer"), INSTALL_opts = "--no-multiarch")
> Error in git2r::fetch(gitrepo, name = "github", credentials = credentials) : 
>   Error in 'git2r_remote_fetch': unknown certificate check failure
> >  
I have that problem on two independent stations

**Comment by leeper** [comment]
Try using `devtools::install_github(c("ropensci/tabulizerjars", "ropensci/tabulizer"))`
