### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by epancotti** [ropensci/tabulizer#78]
I'm having a couple of issues installing tabulizer/tabulizerjars. I think this stems from an rJava issue (unable to load shared object). I read through a few threads and was finally able to get rJava to install and load correctly, but apparently it's preventing devtools::install_github("ropensci/tabulizerjars") from running correctly. I also tried using > ghit::install_github("ropensci/tabulizerjars", INSTALL_opts = "--no-multiarch", verbose = TRUE), and I get an error in git2r_remote_fetch. 

ghit::install_github("ropensci/tabulizerjars", INSTALL_opts = "--no-multiarch", verbose = TRUE)
Parsing reponame for 'ropensci/tabulizerjars'...
Creating local git repository for tabulizerjars in /var/folders/sm/nxjlpmhs451_sn7nhqrkd1rw0000gp/T//Rtmp7CQaK9/tabulizerjars118e33738342c...
Checking out package tabulizerjars to local git repository...
Error in git2r::fetch(gitrepo, name = "github", credentials = credentials) : 
  Error in 'git2r_remote_fetch': SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

devtools::install_github("ropensci/tabulizerjars")
Downloading GitHub repo ropensci/tabulizerjars@master
from URL https://api.github.com/repos/ropensci/tabulizerjars/zipball/master
Installing tabulizerjars
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
 '/private/var/folders/sm/nxjlpmhs451_sn7nhqrkd1rw0000gp/T/Rtmp7CQaK9/devtools118e3af08ef0/ropensci-tabulizerjars-60b7cec'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 
* installing *source* package ‘tabulizerjars’ ...
** R
** inst
** preparing package for lazy loading
Error : .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/rJava/libs/rJava.so
  Reason: image not found
ERROR: lazy loading failed for package ‘tabulizerjars’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/tabulizerjars’
Installation failed: Command failed (1)

sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.2

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.5 rJava_0.9-9     git2r_0.21.0    ghit_0.2.18    

loaded via a namespace (and not attached):
[1] httr_1.3.1     compiler_3.4.3 R6_2.2.2       tools_3.4.3    withr_2.1.1   
[6] curl_3.1       memoise_1.1.0  digest_0.6.15

**Comment by tpaskhalis** [comment]
This looks analogous to #71. Try running `R CMD javareconf` prior to the installation of `rJava`.

**Comment by lnalborczyk** [comment]
None of these solutions work on my machine...(macOS Mojave 10.14, R version 3.5.3). Loading the package with library gives the following error:

internal error -3 in R_decompress1Error: package or namespace load failed for ‘tabulizerjars’ in runHook(".onLoad", env, package.lib, package):
lazy-load database '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tabulizerjars/R/tabulizerjars.rdb' is corrupt

Any idea ?
