### ISSUE TITLE
Appveyor builds and webhook

### ISSUE THREAD

**Issue by maelle** [ropensci/tabulizer#88]
:wave: @leeper!

* The Appveyor builds are under your account, https://ci.appveyor.com/project/leeper/tabulizer. We're currently thinking whether to transfer all Appveyor builds to rOpenSci accounts, but are not going to at the moment, because it seems to have drawbacks, so it's actually fine(/better?) to have them under your account. Could you please update the badge in the README in the meantime so that it points to https://ci.appveyor.com/project/leeper/tabulizer?

* The [Appveyor webhook](https://github.com/ropensci/tabulizer/settings/hooks/9530398) doesn't work. Could you please contact Appveyor support team at  team@appveyor.com ? They'll probably ask for this about the latest delivery (at least that's what they asked for for a repo of mine):

    * X-GitHub-Delivery: 18e37d96-554c-11e8-8988-887a8366b153

    * Time: 2018-05-11 20:49:55

Thank you!

**Comment by leeper** [comment]
Hi @maelle - okay. We're actually in the midst of a maintainership transition. @tpaskhalis is going to be taking over, so maybe it makes sense to do some reconfiguration at this point?

**Comment by maelle** [comment]
Ah then I guess you should make @tpaskhalis admin of this repo, this way he can add Appveyor buils to his account?

@jeroen recommends such badges (pointing to ropensci GitHub repo, but builds under the maintainer's account)

```r
[![AppVeyor Build Status](https://ci.appveyor.com/api/projects/status/github/ropensci/tesseract?branch=master&svg=true)](https://ci.appveyor.com/project/jeroen/tesseract)
```

**Comment by tpaskhalis** [comment]
I don't have access to Appveyor builds now, so would be happy to change badge to @leeper's account to fix the immediate issue as suggested. But would be useful to have admin rights to Appveyor for the future.

**Comment by maelle** [comment]
@tpaskhalis I mean that if you get admin rights to this repo, you can activate Appveyor builds under your Appveyor account and change the badge accordingly so that it points to them :-) (if you don't have an Appveyor account yet it takes very little time to create one, if I remember correctly you can log in with your GitHub account)

**Comment by tpaskhalis** [comment]
@maelle, sure, that might be easier. I have an Appveyor account. Would just need admin rights for this repo.

**Comment by maelle** [comment]
Granted! 😉

**Comment by tpaskhalis** [comment]
Thank you!

**Comment by tpaskhalis** [comment]
Fixed with https://github.com/ropensci/tabulizer/commit/6681dae4aee7c9e52f88de16245bcb6287a52a64.

**Comment by tpaskhalis** [comment]
My bad  :grimacing:. But then `tesseract`'s build looks so much better :wink:.
