### ISSUE TITLE
Can`t install tabulizer on win 8.1 64-bit

### ISSUE THREAD

**Issue by Alexandros11** [ropensci/tabulizer#89]
I got couple errors when trying to install tabulizer package. First i install rJava as suggested:

> install.packages("rJava")
> library("rJava")

Weird thing is that rJava wants always to update some packages and restarting my R session when I install it (I work in Rstudio). But it seems to work correctly. I use this code to install tabulizer:

> ghit::install_github(c("ropenscilabs/tabulizerjars", "ropenscilabs/tabulizer"), INSTALL_opts = "--no-multiarch")

and this is my output:

> also installing the dependencies ‘promises’, ‘later’, ‘httpuv’, ‘sourcetools’
> 
> Error: Package build for tabulizer failed with the following output:
> * checking for file 'C:\Users\ME~1\AppData\Local\Temp\RtmpkrkkVn\tabulizer1c9066a671bb/DESCRIPTION' ... OK
> * preparing 'tabulizer':
> * checking DESCRIPTION meta-information ... OK
> * installing the package to build vignettes
>       -----------------------------------
> ERROR: dependency 'tabulizerjars' is not available for package 'tabulizer'
> * removing 'C:/Users/ME~1/AppData/Local/Temp/Rtmpct4de9/Rinst25c41b55705/tabulizer'
> In R CMD INSTALL
>       -----------------------------------
> ERROR: package installation failed
> In addition: There were 12 warnings (use warnings() to see them)

I am familiar with R but unfortunately lacking any IT/programming background, so this errors are new to me.. Also in "C:/.../ME~1/AppData..." i changed my user name into "ME". I am also new with github, so hopefully i followed all rules asking this question.

**Comment by tpaskhalis** [comment]
Your problem starts earlier, with the installation of `tabulizerjars` package. Which Java version are you using? Make sure that it's not lower than 7. To check this run `java --version` in Windows command line. Try installing `tabulizerjars` with `remotes` instead of `ghit` by running `remotes::install_github(c("ropensci/tabulizerjars"))`.

**Comment by Alexandros11** [comment]
This in unfortunate, when i type `java --version` it prints me:

> Error: Could not create the Virtual Java Machine
> Error: A fatal exception has occurred. Program will exit.

I bet there is silly issue but I can not figure out what it is :(
Installing `tabulizerjars` produces new set of errors...

**Comment by tpaskhalis** [comment]
There is something wrong with your Java installation. I don't think I can diagnose what the problem is. But this needs to be sorted out first, before the installation of `tabulizerjars`. The easiest way would be to re-install the JDK. Also, make sure that the installation of Java is [in your PATH](https://stackoverflow.com/questions/1672281/environment-variables-for-java-installation). After `java --version` works, also re-install `rJava` package. And then install `tabulizerjars` and `tabulizer`.

**Comment by Alexandros11** [comment]
I followed your instructions. Funny thing is when I use `java --version` It produces the same error but when I do `java -version` (only one "-") it prints out:

> java version "1.8.0_171"
> Java(TM) SE Runtime Enviroment (build 1.8.0.)_171-b11)
> Java HotSport(TM) 64-bit server VM (build 25.171-b11, mixed mode)

Errors when I try install `tabulizerjars` usin g`remotes::install_github(c("ropensci/tabulizerjars"))`:

> Downloading GitHub repo ropensci/tabulizerjars@master
> Installing package into ‘C:/Users/Me/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> * installing *source* package 'tabulizerjars' ...
> ** R
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
>   converting help for package 'tabulizerjars'
>     finding HTML links ... done
>     tabulizerjars                           html  
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> Error: package or namespace load failed for 'tabulizerjars':
>  .onLoad failed in loadNamespace() for 'tabulizerjars', details:
>   call: NULL
>   error: .onLoad failed in loadNamespace() for 'rJava', details:
>   call: fun(libname, pkgname)
>   error: JAVA_HOME cannot be determined from the Registry
> Error: loading failed
> Execution halted
> *** arch - x64
> ERROR: loading failed for 'i386'
> * removing 'C:/Users/Me/Documents/R/win-library/3.4/tabulizerjars'
> In R CMD INSTALL
> Warning messages:
> 1: running command '"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\Me\Documents\R\win-library\3.4" "C:/Users/ME~1/AppData/Local/Temp/RtmpA9mjGI/remotes168858592001/ropensci-tabulizerjars-d1924e0"' had status 1 
> 2: In i.p(...) :
>   installation of package ‘C:/Users/ME~1/AppData/Local/Temp/RtmpA9mjGI/remotes168858592001/ropensci-tabulizerjars-d1924e0’ had non-zero exit status

Have I made mistake in setting classpath?

**Comment by tpaskhalis** [comment]
Sorry, yes, it should be with one: `-version`. Does the architecture of your R installation match the Java installation? I.e. are they both 64-bit? What's the output of `sessionInfo()` in R? See [here](https://www.r-statistics.com/2012/08/how-to-load-the-rjava-package-after-the-error-java_home-cannot-be-determined-from-the-registry/).

**Comment by Alexandros11** [comment]
I believe architecture match. I use 64-bit system and I downloaded 64 Java version as well. I set `JAVA_HOME` as in link you posted and wile installing `tabulizerjars` I get this again:

> Downloading GitHub repo ropensci/tabulizerjars@master
> Installing package into ‘C:/Users/Alehandro/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> * installing *source* package 'tabulizerjars' ...
> ** R
> ** inst
> ** preparing package for lazy loading
> ** help
> *** installing help indices
>   converting help for package 'tabulizerjars'
>     finding HTML links ... done
>     tabulizerjars                           html  
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> Error: package or namespace load failed for 'tabulizerjars':
>  .onLoad failed in loadNamespace() for 'tabulizerjars', details:
>   call: NULL
>   error: .onLoad failed in loadNamespace() for 'rJava', details:
>   call: inDL(x, as.logical(local), as.logical(now), ...)
>   error: unable to load shared object 'C:/Users/Alehandro/Documents/R/win-library/3.4/rJava/libs/i386/rJava.dll':
>   LoadLibrary failure:  %1 nie jest prawidlowa aplikacja systemu Win32.
> Error: loading failed
> Execution halted
> *** arch - x64
> ERROR: loading failed for 'i386'
> * removing 'C:/Users/Alehandro/Documents/R/win-library/3.4/tabulizerjars'
> In R CMD INSTALL
> Warning messages:
> 1: running command '"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" CMD INSTALL -l "C:\Users\Alehandro\Documents\R\win-library\3.4" "C:/Users/ALEHAN~1/AppData/Local/Temp/RtmpyYSElH/remotesec437786e4/ropensci-tabulizerjars-d1924e0"' had status 1 
> 2: In i.p(...) :
>   installation of package ‘C:/Users/ALEHAN~1/AppData/Local/Temp/RtmpyYSElH/remotesec437786e4/ropensci-tabulizerjars-d1924e0’ had non-zero exit status

And now my `sessionInfo()` is:

> R version 3.4.3 (2017-11-30)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] rJava_0.9-9
> 
> loaded via a namespace (and not attached):
> [1] compiler_3.4.3 tools_3.4.3    remotes_1.1.1 

How to make sure I installed 64-bit java?

**Comment by tpaskhalis** [comment]
Ok, there is some progress here. This error is different from the previous
one. Java architecture can be determined by running `java -version`, but I
believe it's also 64-bit given the output you posted. Have you re-installed
`rJava` after all these manipulations?

**Comment by Alexandros11** [comment]
Ok maybe issue is actually with `rJava` package because it behaves kind of weird. First of all when I try to reinstall it it pops up this messege: 

https://imgur.com/mEdRH4a

And Rstudio prints out this:

> Installing package into ‘C:/Users/Alehandro/Documents/R/win-library/3.4’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/rJava_0.9-9.zip'
> Content type 'application/zip' length 720033 bytes (703 KB)
> downloaded 703 KB
> 
> package ‘rJava’ successfully unpacked and MD5 sums checked
> Warning in install.packages :
>   cannot remove prior installation of package ‘rJava’
> 
> The downloaded binary packages are in
> 	C:\Users\Alehandro\AppData\Local\Temp\RtmpEpG1Wm\downloaded_packages

I tired to uninstall `rJava` manually using `remove.packages("rJava")` but then I got:

> Removing package from ‘C:/Program Files/R/R-3.4.3/library’
> (as ‘lib’ is unspecified)
> Error in remove.packages : there is no package called ‘rJava’

So I guess `rJava` package path is missing here. But how to get it? When I tried `remove.packages("rJava","C:/Program Files/R/R-3.4.3/library")` it simply returned ` Error in remove.packages : there is no package called ‘rJava’`.

**Comment by tpaskhalis** [comment]
It seems that your `rJava` installation is in a different folder. What does your `.libPaths()` say? It defaults to `"C:/Program Files/R/R-3.4.3/library"` on your system, but the package isn't there. You might want to try to remove it from other directories to which it might have been installed.

**Comment by Alexandros11** [comment]
When I use `.libPaths()`  and it returned:

> "C:/Users/Me/Documents/R/win-library/3.4" "C:/Program Files/R/R-3.4.3/library"
Is it normal I have two different library paths? Or something is messed up with my R/Rstudio?

**Comment by tpaskhalis** [comment]
Yes, the second would typically be used when you launch R/RStudio with Administrator privileges. Try running it as Administrator, purge previous installations of `rJava` from both directories and then re-install `rJava` and `tabulizerjars`.

**Comment by Alexandros11** [comment]
Ok, am I suppose to use `remove.packages("rJava", "path)` or (or if this wont work) remove it all manually by deleting folders?

**Comment by tpaskhalis** [comment]
Yes, try running `remove.packages("rJava","C:/Users/Me/Documents/R/win-library/3.4")` and `remove.packages("rJava","C:/Program Files/R/R-3.4.3/library")` under Admin.

**Comment by Alexandros11** [comment]
This is mine `Sys.getenv()` :

> __COMPAT_LAYER                 Installer
> ALLUSERSPROFILE                C:\ProgramData
> APPDATA                        C:\Users\Me\AppData\Roaming
> CLASS                          C:\Program Files\Java\jdk1.8.0_171\lib
> CLICMER_FORCE                 1
> CommonProgramFiles             C:\Program Files\Common Files
> CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files
> CommonProgramW6432             C:\Program Files\Common Files
> COMPUTERNAME                   ME-LAPTOP
> ComSpec                        C:\WINDOWS\system32\cmd.exe
> configsetroot                  C:\WINDOWS\ConfigSetRoot
> DISPLAY                        :0
> FP_NO_HOST_CHECK               NO
> FRONTLIC                       C:\ProgramData\Frontline Systems\Solver.lic
> GFORTRAN_STDERR_UNIT           -1
> GFORTRAN_STDOUT_UNIT           -1
> HOME                           C:/Users/Me/Documents
> HOMEDRIVE                      C:
> HOMEPATH                       \Users\Me
> JAVA_HOME                      C:/Program Files/Java/jdk1.8.0_171/
> LOCALAPPDATA                   C:\Users\Me\AppData\Local
> LOGONSERVER                    \\MicrosoftAccount
> NewEnvironment1                ;C:\Program Files (x86)\StatSoft\STATISTICA 10\
> NUMBER_OF_PROCESSORS           8
> OS                             Windows_NT
> PATH                           C:\Rtools\bin;C:\Program Files\R\R-3.4.3\bin\x64;C:\Program
>                                Files (x86)\Common
>                                Files\Oracle\Java\javapath;c:\programdata\oracle\java\javapath;c:\program
>                                files (x86)\intel\icls client\;c:\program files\intel\icls
>                                client\;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program
>                                files (x86)\intel\opencl sdk\3.0\bin\x86;c:\program files
>                                (x86)\intel\opencl sdk\3.0\bin\x64;c:\program
>                                files\intel\intel(r) management engine
>                                components\dal;c:\program files\intel\intel(r) management
>                                engine components\ipt;c:\program files (x86)\intel\intel(r)
>                                management engine components\dal;c:\program files
>                                (x86)\intel\intel(r) management engine
>                                components\ipt;c:\program files\intel\wifi\bin\;c:\program
>                                files\common files\intel\wirelesscommon\;d:\program
>                                files\matlab\r2017a\runtime\win64;d:\program
>                                files\matlab\r2017a\bin;C:\Program Files (x86)\NVIDIA
>                                Corporation\PhysX\Common\;C:\Program
>                                Files\Java\jdk1.8.0_171\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program
>                                Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
>                                Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
>                                Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files
>                                (x86)\Intel\OpenCL SDK\3.0\bin\x64;C:\Program
>                                Files\Intel\Intel(R) Management Engine
>                                Components\DAL;C:\Program Files\Intel\Intel(R) Management
>                                Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R)
>                                Management Engine Components\DAL;C:\Program Files
>                                (x86)\Intel\Intel(R) Management Engine
>                                Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program
>                                Files\Common Files\Intel\WirelessCommon\;D:\Program
>                                Files\MATLAB\R2017a\runtime\win64;D:\Program
>                                Files\MATLAB\R2017a\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program
>                                Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
>                                Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0"
> PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
> PROCESSOR_ARCHITECTURE         AMD64
> PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
> PROCESSOR_LEVEL                6
> PROCESSOR_REVISION             3c03
> ProgramData                    C:\ProgramData
> ProgramFiles                   C:\Program Files
> ProgramFiles(x86)              C:\Program Files (x86)
> ProgramW6432                   C:\Program Files
> PSModulePath                   C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
> PUBLIC                         C:\Users\Public
> R_ARCH                         /x64
> R_COMPILED_BY                  gcc 4.9.3
> R_DOC_DIR                      C:/PROGRA~1/R/R-34~1.3/doc
> R_HOME                         C:/PROGRA~1/R/R-34~1.3
> R_LIBS_USER                    C:/Users/Me/Documents/R/win-library/3.4
> R_USER                         C:/Users/Me/Documents
> RMARKDOWN_MATHJAX_PATH         D:/R/RStudio/resources/mathjax-26
> RS_LOCAL_PEER                  \\.\pipe\42112-rsession
> RS_RPOSTBACK_PATH              D:/R/RStudio/bin/rpostback
> RS_SHARED_SECRET               63341846741
> RSTUDIO                        1
> RSTUDIO_CONSOLE_CMER          256
> RSTUDIO_CONSOLE_WIDTH          80
> RSTUDIO_MSYS_SSH               D:/R/RStudio/bin/msys-ssh-1000-18
> RSTUDIO_PANDOC                 D:/R/RStudio/bin/pandoc
> RSTUDIO_SESSION_PORT           42112
> RSTUDIO_USER_IDENTITY          Me
> RSTUDIO_WINUTILS               D:/R/RStudio/bin/winutils
> SystemDrive                    C:
> SystemRoot                     C:\WINDOWS
> TEMP                           C:\Users\ALEHAN~1\AppData\Local\Temp
> TERM                           xterm-256cMEr
> TMP                            C:\Users\ALEHAN~1\AppData\Local\Temp
> USERDOMAIN                     ME-LAPTOP
> USERDOMAIN_ROAMINGPROFILE      ME-LAPTOP
> USERNAME                       Me
> USERPROFILE                    C:\Users\Me
> windir                         C:\WINDOWS

I set my windows PATH accordingly to random youtube tutorial. I will get back to this and do it again step by step, maybe I made mistake somewhere there.

**Comment by tpaskhalis** [comment]
I'm running out of things to try. I got a hold of Windows 8.1 64-bit machine and couldn't replicate any of the issues. The only differences were that I used `R 3.5.0` and `JDK 1.7.0_80`, but I don't think it could be a source of problems. Sounds extreme, but I would try re-installing everything, starting from Java, then R (there is a newer version anyway), then rJava. After installing rJava, try running:
```
library("rJava")
.jinit()
.jcall("java/lang/System","S","getProperty","java.version")
```
And check whether it works and the version matches the one you get when running `java -version` from the command-line. If this all works fine, then proceed to `tabulizerjars`. It's now available on CRAN, so you can just run `install.packages("tabulizerjars")`.

**Comment by Alexandros11** [comment]
when i try to install `tabulizerjars` on new R version (and after reinstalling Java and Java Dev Kit) i got this:

> Installing package into ‘C:/Users/Alehandro/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> Warning in install.packages :
>   package ‘tabulizerjas’ is not available (for R version 3.5.0)

Is this normal? Should I just wait for `tabulizerjars` update for 3.5?

**Comment by tpaskhalis** [comment]
It's misspelled, `r` is missing.

**Comment by tpaskhalis** [comment]
In my case I didn't even have to set JAVA_HOME, as Java was in PATH already. But I did try doing it just to make it more similar to your setup and it worked in both cases. Now, given the error you posted, does `rJava` work just by itself? Did you try loading it after installation with `library("rJava")`?

**Comment by Alexandros11** [comment]
I removed everything from my computer related to R (except Rstudio) now when I try install `tabulizerjars` same error occurs but before that pop up windows show now that i am lacking jvm.dll... It does not matter whether `rJava` is active. And if it is, after error it unchecks in Rstudio package list. Just to fulfill or formalities here is error, however I believe it is same as previous ones (or very similar at least):

> install.packages("tabulizerjars")
> Installing package into ‘C:/Users/Alehandro/Documents/R/win-library/3.5’
> (as ‘lib’ is unspecified)
> installing the source package ‘tabulizerjars’
> 
> trying URL 'https://cran.rstudio.com/src/contrib/tabulizerjars_1.0.1.tar.gz'
> Content type 'application/x-gzip' length 10902674 bytes (10.4 MB)
> downloaded 10.4 MB
> 
> * installing *source* package 'tabulizerjars' ...
> ** package 'tabulizerjars' successfully unpacked and MD5 sums checked
> ** R
> ** inst
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
>   converting help for package 'tabulizerjars'
>     finding HTML links ... done
>     tabulizerjars                           html  
> ** building package indices
> ** testing if installed package can be loaded
> *** arch - i386
> Error: package or namespace load failed for 'tabulizerjars':
>  .onLoad failed in loadNamespace() for 'tabulizerjars', details:
>   call: NULL
>   error: .onLoad failed in loadNamespace() for 'rJava', details:
>   call: inDL(x, as.logical(local), as.logical(now), ...)
>   error: unable to load shared object 'C:/Users/Alehandro/Documents/R/win-library/3.5/rJava/libs/i386/rJava.dll':
>   LoadLibrary failure:  Nie mozna odnalezc okreslonego modulu.
> 
> Error: loading failed
> Execution halted
> *** arch - x64
> Error: package or namespace load failed for 'tabulizerjars':
>  .onLoad failed in loadNamespace() for 'tabulizerjars', details:
>   call: NULL
>   error: .onLoad failed in loadNamespace() for 'rJava', details:
>   call: inDL(x, as.logical(local), as.logical(now), ...)
>   error: unable to load shared object 'C:/Users/Alehandro/Documents/R/win-library/3.5/rJava/libs/x64/rJava.dll':
>   LoadLibrary failure:  Nie mozna odnalezc okreslonego modulu.
> 
> Error: loading failed
> Execution halted
> ERROR: loading failed for 'i386', 'x64'
> * removing 'C:/Users/Alehandro/Documents/R/win-library/3.5/tabulizerjars'
> In R CMD INSTALL
> Warning in install.packages :
>   installation of package ‘tabulizerjars’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘C:\Users\Alehandro\AppData\Local\Temp\RtmpM5rZ3e\downloaded_packages’

**Comment by tpaskhalis** [comment]
What do you mean by `rJava` being active? Just to confirm whether the problem is on `tabulizerjars` or `rJava` side. Does the following work?
```
library("rJava")
.jinit()
.jcall("java/lang/System","S","getProperty","java.version")
```

**Comment by Alexandros11** [comment]
By "being active" its checkbox in Rstudio package list is selected. Your code do this:;

> library("rJava")
> .jinit()
> .jcall("java/lang/System","S","getProperty","java.version")
> [1] "1.8.0_171"

**Comment by tpaskhalis** [comment]
Thank you for trying. Looking at the code you posted above, I can venture one more guess. `ERROR: loading failed for 'i386'` after you set the correct JAVA_HOME means that it still tries to use x86 architecture. Which is strange, given that you have 64-bit version. When installing R do you tick the boxes for both x86 and x64 by any chance?

**Comment by Alexandros11** [comment]
THATS IT! I mean partially it. During my R installation I didnt have option to select x86, but I had option to install both R version: 32bit and 64bit which I always did automatically. And this was the reason! Now i selected only 64bit and `tabulizerjars` as well as `tabulizer` were installed correctly. 

Thank you very much tpaskhalis for all your support and solving my issue (you can mark is as solved). 

Also I think it is important to note for the future users, that when you install both R architectures versions it may crash `tabulizerjars` package installation (even if you using only 64bit/32bit R).

**Comment by tpaskhalis** [comment]
Thank you for perseverance! Yes, I have writing comprehensive installation instructions on my plan. It's interesting to note that the parallel install of 32-bit and 64-bit R didn't seem to cause any problems for `xslx` as you said. Maybe there is something that could be done on the package side, I'll need to look into that.
