### ISSUE TITLE
Installation OSx High Sierra related to jdk version 10 vs. 9

### ISSUE THREAD

**Issue by technocrat** [ropensci/tabulizer#92]
Both tabulizer and rJava throw the same error:

> library(tabulizer)
     Error: package or namespace load failed for ‘tabulizer’:
      .onLoad failed in loadNamespace() for 'tabulizerjars', details:
       call: NULL
       error: .onLoad failed in loadNamespace() for 'rJava', details:
       call: dyn.load(file, DLLpath = DLLpath, ...)
       error: unable to load shared object '/Users/rc/Library/R/3.5/library/rJava/libs/rJava.so':
       dlopen(/Users/rc/Library/R/3.5/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
       Referenced from: /Users/rc/Library/R/3.5/library/rJava/libs/rJava.so
       Reason: image not found
     > library(rJava)
     Error: package or namespace load failed for ‘rJava’:
      .onLoad failed in loadNamespace() for 'rJava', details:
       call: dyn.load(file, DLLpath = DLLpath, ...)
       error: unable to load shared object '/Users/rc/Library/R/3.5/library/rJava/libs/rJava.so':
       dlopen(/Users/rc/Library/R/3.5/library/rJava/libs/rJava.so, 6): Library not loaded:    /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
       Referenced from: /Users/rc/Library/R/3.5/library/rJava/libs/rJava.so
       Reason: image not found
  
Note that both are specifically looking for jdk-9.jdk. As part of my set-up for this, I installed the current Java JDK, which is now at 

    JAVA_HOME        : /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home

a higher version. I have only a bit of scraping to do, so I'm not looking for a workaround, just reporting for the good of the cause.

**Comment by tpaskhalis** [comment]
That is an `rJava` issue, not `tabulizer`. Have you tried running `R CMD javareconf` after installing the new version?

**Comment by technocrat** [comment]
I'll confess to near-zero experience with CMD and its cousins like devtools::RCMD, and I'm missing arguments. Maybe it's my repugnance to Java (from using it in a very early version), but I'm going to have to wait until a more urgent need arises. But it does seem that if rJava has jdk hardwired, I'd have to downversion to have any chance to get things working. Thanks for the suggestion, though.

**Comment by tpaskhalis** [comment]
Usually there is no need to downgrade.
A typical upgrade work flow would be: Upgrade Java -> Run `R CMD javareconf` -> Upgrade rJava
